version: "3"
services:
  # https://hub.docker.com/_/nextcloud
  app:
    image: nextcloud:${X_NEXTCLOUD_IMAGE_TAG:-28.0.3-fpm}
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      NEXTCLOUD_DATA_DIR: /data
      NEXTCLOUD_ADMIN_USER: ${X_NEXTCLOUD_ADMIN_USER:-nextcloud}
      NEXTCLOUD_ADMIN_PASSWORD: ${X_NEXTCLOUD_ADMIN_PASSWORD:-nextcloud}
      NEXTCLOUD_TRUSTED_DOMAINS: ${X_NEXTCLOUD_TRUSTED_DOMAINS:-}
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ${X_MYSQL_DATABASE:-nextcloud}
      MYSQL_USER: ${X_MYSQL_USER:-nextcloud}
      MYSQL_PASSWORD: ${X_MYSQL_PASSWORD:-nextcloud}
      REDIS_HOST: redis
      REDIS_HOST_PORT: 6379
      REDIS_HOST_PASSWORD: ${X_REDIS_PASSWORD:-NOT_SAFE}
      OVERWRITEPROTOCOL: ${X_PROTOCOL:-http}
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.nextcloud.schedule: "@every 5m"
      ofelia.job-exec.nextcloud.command: "php cron.php"
      ofelia.job-exec.nextcloud.user: www-data
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
      - ./custom_apps:/var/www/html/custom_apps
      - ./config:/var/www/html/config
      - ./data:/data
  collabora:
    image: collabora/code:${X_COLLABORA_IMAGE_TAG:-23.05.10.1.1}
  # https://hub.docker.com/_/mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${X_MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${X_MYSQL_DATABASE:-nextcloud}
      MYSQL_USER: ${X_MYSQL_USER:-nextcloud}
      MYSQL_PASSWORD: ${X_MYSQL_PASSWORD:-nextcloud}
      LANG: C.UTF-8
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: unless-stopped
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d:ro
      - ./docker/mysql/zz-00.cnf:/etc/mysql/conf.d/zz-00.cnf:ro
      - mysql_data:/var/lib/mysql
  nginx:
    image: nginx:1.24-alpine
    depends_on:
      - app
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
      - ./custom_apps:/var/www/html/custom_apps:ro
      - ./docker/nginx/nextcloud.conf:/etc/nginx/nginx.conf:ro
  ofelia:
    image: mcuadros/ofelia:0.3.10
    command: daemon --docker -f label=com.docker.compose.project=${COMPOSE_PROJECT_NAME}
    depends_on:
      - app
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  # https://hub.docker.com/_/redis
  redis:
    image: redis:6.2-alpine
    command: ["redis-server", "--requirepass", "${X_REDIS_PASSWORD:-NOT_SAFE}"]
    networks:
      - default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    volumes:
      - redis_data:/data
volumes:
  mysql_data:
    driver: local
  nextcloud:
    driver: local
  redis_data:
    driver: local
